### ISSUE TITLE
Proposition: composition of predicates

### ISSUE THREAD

**Issue by Gladear** [akoutmos/unplug#5]
Hi there!
I'm wondering if it'd be interesting to add a built-in way to compose predicates, so for example, execute a Plug only if two predicates match.

I was think of something like the following for the API:
```ex
  plug Unplug,
    if: {Unplug.Compose.All, [
          {Unplug.Predicates.RequestPathNotIn, ["/metrics", "/healthcheck"]},
          {Unplug.Predicates.AppConfigEquals, {:my_app, :some_config, :enabled}
        ]},
    do: Plug.Telemetry
```

This would require all conditions to be met. Another `Unplug.Compose.Any` could pass if one of the predicates matches.

What do you think about this?
I'm willing to work on the implementation if this is something the library can accept 😄

**Comment by akoutmos** [comment]
Hey there! Sorry for the delay...the notification for this must have gotten lost in the inbox. This is a really good idea and something I would definitely merge into the project.

I like the idea of having it be is't own predicate like you have in your `Unplug.Compose.All` example as it opens up the possibility to also support `Any` as you describe. Looking forward to your PR :)

**Comment by akoutmos** [comment]
Merged in your changes and will be cutting a release soon!
